---
- name: 'Update environment variables, master key and restart nginx'
  hosts: web
  user: "{{ deploy_user }}"
  become_user: "{{ deploy_user }}"

  vars_files:
    - vars/vars.yml
    - vars/envs.yml

  tasks:
    - name: Create [project] directory
      file:
        path: "/home/{{ deploy_user }}/{{ app_name }}"
        state: directory
        owner: "{{ deploy_user }}"
        group: "{{ deploy_user }}"

    - name: Create shared config directory
      file:
        path: "/home/{{ deploy_user }}/{{ app_name }}/shared/config"
        state: directory
        owner: "{{ deploy_user }}"
        group: "{{ deploy_user }}"

    - name: Update master key
      template:
        src: templates/master.key.j2
        dest: "/home/{{ deploy_user }}/{{ app_name }}/shared/config/master.key"
        owner: "{{ deploy_user }}"
        group: "{{ deploy_user }}"

    - name: Update database.yml for production
      template:
        src: templates/database.key.j2
        dest: "/home/{{ deploy_user }}/{{ app_name }}/shared/config/database.yml"
        owner: "{{ deploy_user }}"
        group: "{{ deploy_user }}"

    - name: Restart nginx service
      service:
        name: nginx
        state: restarted
      become: true