- name: Check if a certificate already exists
  stat:
    path: /etc/letsencrypt/live/{{ domain | replace('*.', '') }}/cert.pem
  register: letsencrypt_cert

- name: Get new certificate
  command: "certbot --nginx -m {{ certbot_email }} -d {{ domain }} --agree-tos {{ certbot_flags }} --non-interactive"
  when: not letsencrypt_cert.stat.exists
  notify: Restart nginx